name: Build, test and deploy
on:
  push:
    paths-ignore:
      - "*.md"
env:
  DOCKER_REPOSITORY: acouvreur/ssh-log-to-influx
  CI: true

jobs:
  build:
    name: Build, test, Docker artifact and deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Install Dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Test
        run: npm test

      - name: Docker build and push
        uses: docker/build-push-action@v1
        if: 
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: ${{ env.DOCKER_REPOSITORY }}
          tag_with_ref: true
          add_git_labels: true
